name: publish

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  npm:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Cloning
      - uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      #     registry-url: "https://registry.npmjs.org"
      # - run: npm install
      # # Publish to npm
      # - run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      
      
      # Setup NPM git registery (TODO remove if working)
      - name: "Setup npm" # Add our registry to npm config
        run: | # Custom action
          npm set @syntest:registry=https://npm.pkg.github.com/syntest
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      # Version and publish 
      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          if [ ${{ github.base_ref }} = development ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          else
            npx lerna version --conventional-commits --conventional-graduate --yes
          fi

          npx lerna publish from-git --yes
