name: publish

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  npm:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Cloning
      - uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      # Configure git user
      - name: Config git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      # Bootstrap
      - name: Bootstrap lerna
        run: npx lerna bootstrap

      # Version and publish
      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
        run: |
          if [ ${{ github.base_ref }} = develop ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          else
            npx lerna version --conventional-commits --conventional-graduate --yes
          fi

          npx lerna publish from-git --yes
