name: check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      # Cloning
      - uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      # Setup
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      # Caching
      - name: Get NPM cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      # Dependencies
      - name: Framework - Install Dependencies
        run: npm install --dev

      # Check format
      - name: Framework - Run Format Checker
        run: npm run format:check

      # Check linting
      - name: Framework - Run Linter
        run: npm run lint
