name: verify

on:
  pull_request:
    paths-ignore:
      - "docs/"
      - "**.md"

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: "."
    strategy:
      # Keep running other versions when a job fails
      fail-fast: false

      matrix:
        # Run the pipeline on all the currently supported OS versions
        os: [ubuntu-latest]

        # Run the pipeline on all the currently supported LTS versions and the upcoming version
        node-version: [18]

        # Run the pipeline on all the currently supported architectures
        architecture: [x64]

    steps:
      # Cloning
      - uses: actions/checkout@v3

      # Setup
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}

      # Caching
      - name: Get NPM cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      # Dependencies
      - name: Core - Install Dependencies
        run: |
          npm ci

      # Formatting
      - name: Core - Run Formatter
        run: npm run lerna:format:check

      # Linting
      - name: Core - Run Linter
        run: npm run lerna:lint
