name: version-release

on:
  push:
    types: [created]
    branches:
      - 'release/**'

jobs:
  version-release:
    runs-on: ubuntu-latest
    steps:
      # Cloning
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SYNTEST_CI }}

      # Setup .npmrc file to publish to npm
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

      # Configure git user
      - name: Config git user
        run: |
          git config --global user.name 'SynTest CI'
          git config --global user.email 'info@syntest.org'

      # Bootstrapping
      - name: Core - Install Dependencies
        run: |
          npm ci

      # Building
      - name: Core - Build
        run: npm run lerna:build:compile

      # Versioning
      - name: "Core - Version"
        env:
          GH_TOKEN: ${{ secrets.SYNTEST_CI }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
        run: |
          npx lerna version --conventional-commits --conventional-graduate  --changelog-preset conventionalcommits --create-release github --yes --loglevel silly
